### ISSUE TITLE
Hec token in cleartext - support for secrets manager instead

### ISSUE THREAD

**Issue by aws-spark** [mosajjal/whatthehec#4]
A feature request for a nice to have would be the ability to call the Hec token from secrets manager rather than store it in cleartext as env variable.

**Comment by mosajjal** [comment]
Added an untested feature to fetch the HEC token automatically from AWS Secrets Manager, when HEC token starts with `arn:aws:secretsmanager`. It uses the same role and permission as S3's credentials at the moment. Please test and report back if it's working.
